http:
  server_address: "8000"
  server_port: "8000"
  context_timeout: 10s

postgres:
  db_host: db
  db_port: 5432
  db_user: postgres
  db_name: learning_service
  db_password: postgres
  db_sslmode: disable

auth:
  password_salt: sdfas

  jwt:
    access_token_expiry_time: 15m
    refresh_token_expiry_time: 720h
    signing_key: dsfdsfdsfdsf
